(dp1
S'output'
p2
S'<type \'exceptions.RuntimeError\'> Failure to connect, tried 5 times:\nTraceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 7845, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 688, in __call__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2728, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 648, in reconnect\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2726, in connector\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/__init__.py", line 93, in Connect\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 575, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 741, in _connect\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 796, in _request_authentication\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 845, in _send_authentication\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 341, in check_error\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/err.py", line 142, in raise_mysql_exception\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/err.py", line 135, in _check_mysql_exception\nOperationalError: (1045, u"Access denied for user \'admin\'@\'localhost\' (using password: YES)")\n'
p3
sS'layer'
p4
S'C:\\Users\\Uriel\\Desktop\\UnB\\CJR\\G\xeanios\\web2py\\applications\\Genios\\models\\db.py'
p5
sS'code'
p6
S'db = DAL(\'mysql://admin:admin5@localhost/mydb\',migrate=False,lazy_tables=True) # Conecta com o banco\n\nfrom gluon.tools import Auth, Crud, Service, PluginManager, prettydate\nauth = Auth(db)\ncrud, service, plugins = Crud(db), Service(), PluginManager()\n\n\n\ndb.define_table(\'tb_filho\',\n                Field(\'foto\',\'upload\', uploadfield=\'foto_arquivo\'),\n                Field(\'foto_arquivo\',\'blob\'),Field(\'ativo\',\'boolean\'),\n                Field(\'nome\',requires=IS_NOT_EMPTY()),\n                Field(\'colegio\',requires=IS_NOT_EMPTY()),\n                Field(\'ano\',\'integer\'))\n\ndb.define_table(\'tb_pai_x_filho\',Field(\'fk_pai\',\'reference tb_usuario\'),Field(\'fk_filho\',\'reference tb_filho\') )\n\ndb.define_table(\'tb_perfil\',\n                Field(\'id_perfil\',\'id\'),\n                Field(\'nome\',\'string\'),\n                Field(\'ativo\',\'integer\'),\n                redefine=True,\n                format = \'%(nome)s\')\n\n\n\'\'\'db.define_table("tb_usuario",\n                Field(\'id_usuario\',\'id\'),\n                Field(\'nome\'),\n                Field(\'fk_id_perfil\',\'reference tb_perfil\'),\n                Field(\'email\'),\n                Field(\'senha\',\'password\'),\n                Field(\'numero_filhos\',\'integer\'),\n                Field(\'ano_escolar\',\'integer\'),\n                Field(\'ativo\',\'boolean\'),\n                Field(\'foto_nome\',\'upload\',uploadfield=\'foto\'),\n                Field(\'foto\',\'blob\'),\n                redefine=True,\n                format = \'%(nome)s\')\'\'\'\n\ndb.define_table(\'tb_usuario\',\n\tField(\'id_usuario\',\'id\'),\n\tField(\'fk_id_perfil\',\'reference tb_perfil\',required=True,requires=IS_IN_DB(db,db.tb_perfil.id_perfil,\'%(nome)s\')),\n\tField(\'nome\',\'string\',length=80,required=True),\n\tField(\'email\',\'string\',required=True,length=200),\n\tField(\'senha\',\'password\',required=True,length=128),\n    Field(\'ano_escolar\',\'int\'),\n\tField(\'colegio\',\'string\',length=70),\n    Field(\'ativo\',\'boolean\'),\n    redefine=True,\n    format = \'%(nome)s\')\n\n\n\ndb.define_table(\'tb_operacao\',\n                Field(\'nome\', length=128, default=\'\'),\n                redefine=False\n                )\n\ndb.define_table(\'tb_erro\',\n                Field(\'excessao\', \'text\')\n                )\n\ndb.define_table(\'tb_pais\',\n                Field(\'nome\', length=128, default=\'\'),\n                Field(\'ativo\',\'boolean\')\n                )\n\ndb.define_table(\'tb_estado\',\n                Field(\'fk_id_pais\',\'reference tb_pais\'),\n                Field(\'nome\', length=128, default=\'\'),\n                Field(\'ativo\',\'boolean\')\n                )\n\ndb.define_table(\'tb_cidade\',\n                Field(\'id_cidade\',\'id\'),\n                Field(\'nome\', length=128, default=\'\'),\n                Field(\'ativo\',\'boolean\'),\n                format= \'%(nome)s\'\n                )\n\ndb.define_table(\'tb_endereco\',\n                Field(\'id_endereco\',\'id\'),\n                Field(\'fk_id_cidade\',\'reference tb_cidade\'),\n                Field(\'fk_id_usuario\',\'reference tb_usuario\'),\n                Field(\'endereco\', length=200, default=\'\'),\n                Field(\'complemento\', length=200, default=\'\'),\n                Field(\'cep\'),\n                Field(\'ativo\',\'boolean\')\n                )\n\ndb.define_table(\'tb_telefone\',\n                Field(\'id_telefone\',\'id\'),\n                Field(\'numero\'),\n                Field(\'fk_id_usuario\',\'reference tb_usuario\'),\n                Field(\'ativo\',\'boolean\')\n                )\n\ndb.define_table(\'tb_curso\',\n                Field(\'nome\', length=200, default=\'\'),\n                Field(\'ativo\',\'boolean\')\n                )\n\ndb.define_table(\'ta_usuario_x_curso\',\n                Field(\'fk_id_usuario\',\'reference tb_usuario\'),\n                Field(\'fk_id_curso\',\'reference tb_curso\'),\n                Field(\'semestre\', \'integer\'),\n                Field(\'ativo\',\'boolean\')\n                )\n\ndb.define_table(\'tb_materia\',\n                Field(\'nome\', length=200, default=\'\'),\n                Field(\'ativo\',\'boolean\')\n                )\n\ndb.define_table(\'ta_usuario_x_materia\',\n                Field(\'fk_id_usuario\',\'reference tb_usuario\'),\n                Field(\'fk_id_materia\',\'reference tb_materia\'),\n                Field(\'ativo\',\'boolean\')\n                )\n\n# HORARIO\ndb.define_table(\'tb_horario_livre\',\n                Field(\'fk_id_usuario\',\'reference tb_usuario\'),\n                Field(\'horario_inicial\', \'time\'),\n                Field(\'horario_final\', \'time\'),\n                Field(\'data_horario_livre\', \'date\', requires=IS_DATE(\'%m/%d/%Y\')),\n                Field(\'ativo\',\'boolean\')\n                )\n\n# PROFESSOR\ndb.define_table(\'tb_professor\',\n                Field(\'nome\', length=128, default=\'\'),\n                Field(\'email\', length=128, default=\'\'),\n                Field(\'senha\', \'password\', length=512, readable=False),\n                Field(\'instEns\', length=128, default=\'\'),\n                Field(\'curso\', length=128, default=\'\'),\n                Field(\'semestre\', \'integer\'),\n                Field(\'ativo\',\'boolean\'),\n                Field(\'foto\', \'upload\'),\n                Field(\'fk_id_perfil\',\'reference tb_perfil\'),\n                Field(\'foto_nome\',\'upload\',uploadfield=\'foto\'),\n                Field(\'foto\',\'blob\'),\n                redefine=False,\n                format = \'%(nome)s\')\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/restricted.py", line 220, in restricted\n  File "C:\\Users\\Uriel\\Desktop\\UnB\\CJR\\G\xeanios\\web2py\\applications\\Genios\\models\\db.py", line 1, in <module>\n    db = DAL(\'mysql://admin:admin5@localhost/mydb\',migrate=False,lazy_tables=True) # Conecta com o banco\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 7867, in __init__\nRuntimeError: Failure to connect, tried 5 times:\nTraceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 7845, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 688, in __call__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2728, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 648, in reconnect\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2726, in connector\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/__init__.py", line 93, in Connect\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 575, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 741, in _connect\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 796, in _request_authentication\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 845, in _send_authentication\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 341, in check_error\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/err.py", line 142, in raise_mysql_exception\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/err.py", line 135, in _check_mysql_exception\nOperationalError: (1045, u"Access denied for user \'admin\'@\'localhost\' (using password: YES)")\n\n'
p11
s.